# Generated by Django 3.1 on 2020-08-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
